// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/tenable_audit_log component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("tenable_audit_log")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/tenableauditlogreceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
