// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("crowdstrike")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/crowdstrikereceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
