// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the connector/bytes component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("bytes")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/connector/bytesconnector"
)

const (
	LogsToMetricsStability = component.StabilityLevelAlpha
)
