// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/idira component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("idira")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/idirareceiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
